name: Detect Deleted Files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect_deleted_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Detect deleted files
      run: |
        git fetch origin ${{ github.event.pull_request.base.sha }} --depth=1
        git diff --name-only FETCH_HEAD ${{ github.event.pull_request.head.sha }} | grep '^deleted_file_path/' && exit 1 || exit 0
